---
- name: debug module demo.
  hosts: all
  vars: 
    variable1: |-
      exactly as you see 
      will appear these three
      lines of poetry.
    variable2: >-
      this is really 
      single line of text
      despite appreances
  tasks:
    - name: print variable1
      ansible.builtin.debug:  
        var: variable1
    - name: print variable2
      debug:
        var: variable2
  