---
- name: date and time demo
  hosts: all
  gather_facts: true
  tasks:  
    - name: date and time
      debug:
        var: ansible_date_time
    - name: ISO8601
      debug:
        var: ansible_date_time.iso8601
    - name: Print date
      debug:
        var: ansible_date_time.date