---
- name: debug module damo
  hosts: all
  vars:
    fruit: "apple"
  tasks: 
    - name: print message
      ansible.builtin.debug:
        var: fruit
    - name: print message
      ansible.builtin.debug:
        msg: "My fruit is {{ fruit }}"
        verbosity: 2