---
- name: root login demo
  hosts: all
  become: true
  gather_facts: false
  tasks: 
    - name: ssh permitrootlogin
      lineinfile:
        dest: /etc/ssh/sshd_config
        regex: '^PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
      notify: ssh restart
  handlers:
    - name: ssh restart
      ansible.builtin.service:
        name: sshd
        state: restarted