---
- name: copy module demo.
  hosts: all
  vars: 
    fruit: "banana"
    output: "output.txt"
  tasks:  
    - name: write to file.
      copy: 
        content: "{{ fruit }}"
        dest: "{{ output }}"